baseURL = "https://emil28092005.github.io/"
languageCode = "ru"
title = "Emil Shanayev"

[params]
  author = "Emil Shanayev"
  description = "DevOps & Backend Engineer"
  keywords = ["DevOps", "Backend", "Go", "Tailwind", "Resume"]
  github = "https://github.com/emil28092005"
  email = "emil28092005@gmail.com"
